---
title: Contoh Sequence Diagram
---
sequenceDiagram
    autonumber
    actor Nasabah
    participant ATM as Mesin ATM
    participant Bank as Sistem Bank

    Nasabah->>+ATM: masukkanKartu(kartu)
    ATM->>Nasabah: mintaPIN()
    Nasabah->>ATM: inputPIN(pin)
    ATM->>+Bank: verifikasiPIN(kartu, pin)
    Bank-->>-ATM: hasilVerifikasi: valid
    ATM-->>Nasabah: tampilkanMenu()

    Nasabah->>ATM: pilihTarikTunai(500000)
    ATM->>+Bank: debitSaldo(akun, 500000)
    Bank->>Bank: validasiSaldo()
    Bank-->>-ATM: konfirmasiDebit: sukses

    par Pesan Asinkron
        ATM--)Bank: logTransaksi(detail)
    and
        ATM->>Nasabah: keluarkanUang(500000)
    end
    ATM->>Nasabah: cetakStruk()
    deactivate ATM
